export const CreateProductsFields = [
  {
    id: 'title',
    name: 'title',
    label: 'Title',
    placeholder: 'Enter title',
    type: 'text',
  },
  {
    id: 'description',
    name: 'description',
    label: 'Description',
    placeholder: 'Enter description',
    type: 'text',
  },
  {
    id: 'trade_mark',
    name: 'trade_mark',
    label: 'Trade Mark',
    placeholder: 'Enter trade mark',
    type: 'text',
  },
  {
    id: 'price',
    name: 'price',
    label: 'Price',
    placeholder: 'Enter price',
    type: 'text',
  },
  {
    id: 'olrd_price',
    name: 'olrd_price',
    label: 'Old Price',
    placeholder: 'Enter old price',
    type: 'text',
  },
  {
    id: 'size',
    type: 'multi-select',
    label: 'Size',
    name: 'size',
    placeholder: 'Select Size',
    options: ['XL', 'XXL', 'Small', 'Large'],
  },
  {
    id: 'discount',
    name: 'discount',
    label: 'Discount',
    placeholder: 'Enter discount',
    type: 'text',
  },
  {
    id: 'image',
    name: 'image',
    label: 'Image',
    placeholder: 'Add Image',
    type: 'file',
  },
  {
    id: 'gallery',
    name: 'gallery',
    label: 'Gallery',
    placeholder: 'Add Gallery Image',
    type: 'file',
  },
];
