export const CreateProductsFields = [
  {
    id: 'title',
    name: 'title',
    label: 'Title',
    placeholder: 'Enter title',
    type: 'text',
  },
  {
    id: 'description',
    name: 'description',
    label: 'Description',
    placeholder: 'Enter description',
    type: 'text',
  },
  {
    id: 'trade_mark',
    name: 'trade_mark',
    label: 'Trade Mark',
    placeholder: 'Enter trade mark',
    type: 'text',
  },
  {
    id: 'section',
    name: 'section',
    label: 'Section',
    placeholder: 'Select section',
    type: 'select',
  },
  {
    id: 'category',
    name: 'category',
    label: 'Category',
    placeholder: 'Select category',
    type: 'select',
  },
  {
    id: 'price',
    name: 'price',
    label: 'Price',
    placeholder: 'Enter price',
    type: 'number',
  },
  {
    id: 'old_price',
    name: 'old_price',
    label: 'Old Price',
    placeholder: 'Enter old price',
    type: 'number',
  },
  {
    id: 'discount',
    name: 'discount',
    label: 'Discount',
    placeholder: 'Enter discount',
    type: 'number',
  },
  {
    id: 'size',
    type: 'multi-select',
    label: 'Size',
    name: 'size',
    placeholder: 'Select Size',
    options: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'image',
    name: 'image',
    label: 'Image',
    placeholder: 'Add Image',
    type: 'file',
  },
  {
    id: 'gallery',
    name: 'gallery',
    label: 'Gallery',
    placeholder: 'Add Gallery Image',
    type: 'file',
  },
];
